name: pangeo
channels:
  - conda-forge
dependencies:
  - rasterio
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - gcsfs
  - intake
  - intake-xarray
  - s3fs
  - fsspec
  - scikit-image
  - scikit-learn
  - dask-ml
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz/label/dev::datashader
  - pyviz/label/dev::geoviews
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab
  - ipywidgets
  - ipyleaflet
  - dask-kubernetes
  - tornado=5.1.1
  - python-wget
  - pip
  - pip:
    - graphviz
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension 
